#!/bin/sh

if [ $# = 1 ]
then
    server="aesdsocket"
    if [ "$1" = "start" ]
    then
        start-stop-daemon -v -S -x $server
    elif [ "$1" = "stop" ]
    then
        start-stop-daemon -v -K -x $server
    fi
fi
